version: '3.9'

services:

  user:
    build:
      context: user
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      - FLASK_APP=main
      - FLASK_DEBUG=1
      - FLASK_ENV=production
      - DB_HOST=users_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users_db
      - SECRET_TOKEN=token-super-secreto
      - VERSION=1.0
    depends_on:
      - users_db
    networks:
      - user_net
      - app_net
    
  users_db:
    image: postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    networks:
      - user_net

volumes:
  pgdata_user:

networks:
  user_net:
    driver: bridge
  app_net:
    driver: bridge
    